using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using RhinoAI.Router;
using RhinoAI.Router.Tools.Generated;

RouterConfig config = RouterConfig.FromArgs(args);

string informationalVersion =
    Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion
    ?? throw new InvalidOperationException("router assembly missing InformationalVersion; check build config");
string routerVersion = informationalVersion.Split('+')[0];

// C. Sykes 5th Sept 2026 - RH-97810
// Ensure app has a reasonable root dir, to prevent unnecessary file watcher checks
HostApplicationBuilder builder = Host.CreateApplicationBuilder(new HostApplicationBuilderSettings
{
    Args = args,
    // Give a reasonable root default
    ContentRootPath = AppContext.BaseDirectory,
    // Prevent File Watchers
    DisableDefaults = true,
});

// Stdio MCP servers must not log to stdout — that's the JSON-RPC channel.
// Route all logging to stderr.
builder.Logging.ClearProviders();
builder.Logging.AddConsole(o => o.LogToStandardErrorThreshold = LogLevel.Trace);

builder.Services.AddSingleton(config);
builder.Services.AddSingleton<RhinoControlClient>();
builder.Services.AddSingleton<RhinoCrashReportFinder>();
builder.Services.AddSingleton<SlotStore>();
builder.Services.AddSingleton<RhinoManager>();
builder.Services.AddSingleton<ProxyDispatcher>();
builder.Services.AddSingleton<RouterId>();
builder.Services.AddHttpClient();

// JsonSerializerOptions used by the MCP server for tool arg/return serialization.
// Source-generated RouterJsonContext is chained first so AOT publish stays clean;
// MCP layers its own context on top of whatever we pass in.
JsonSerializerOptions jsonOptions = new (JsonSerializerDefaults.Web);
jsonOptions.TypeInfoResolverChain.Insert(0, RouterJsonContext.Default);
jsonOptions.Converters.Add(new LenientStringConverter());

IMcpServerBuilder mcpBuilder = builder.Services
    .AddMcpServer(o =>
    {
        o.ServerInfo = new() { Name = "rhino-mcp-router", Version = routerVersion };
    })
    .WithStdioServerTransport();

// Replaces WithToolsFromAssembly() — that path uses Assembly.GetCallingAssembly()
// which is unsupported under NativeAOT. RouterToolRegistrar is generated by
// codegen and chains WithTools<T>() per tool class.
RouterToolRegistrar.RegisterAll(mcpBuilder, jsonOptions);

IHost host = builder.Build();

// Adopt any user-started Rhinos that announced themselves before the router
// came up. Cheap one-shot dir scan; later scans happen on every list_slots
// and slot-less dispatch.
host.Services.GetRequiredService<RhinoManager>().ScanAnnouncements();

// Clean up child Rhinos when Claude Code closes the stdio connection.
host.Services.GetRequiredService<IHostApplicationLifetime>().ApplicationStopping.Register(() =>
{
    host.Services.GetRequiredService<RhinoManager>().CloseAll();
});

await host.RunAsync();
